# Theme colors
thm_orange="#ff9e64"
thm_black="#000000"

# Basic settings
# Set prefix to C-a
set -g prefix C-a
## Remove old prefix
unbind C-b
## Send C-a to apps by pressing it twice
bind C-a send-prefix

# Options
## Window and pane indices
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

## Other
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g history-limit 1000000
set -g set-clipboard on

# Bindings
## Window splitting
unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
bind z split-window -v -c "#{pane_current_path}"

## Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind u select-pane -t "{next}" # Go to the next pane.
bind i select-pane -t "{previous}" # Go to the previous pane.
bind o select-pane -t "{last}" # Go to the last pane.

## Pane resizing
bind H resize-pane -L 2
bind J resize-pane -D 2
bind K resize-pane -U 2
bind L resize-pane -R 2
bind g resize-pane -Z # maximize pane

# Copy mode changes
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# uncomment this if mouse scroll shouldn't enter copy-mode
# unbind -T copy-mode-vi MouseDragEnd1Pane

# Pane colors
set -g pane-border-style "fg=#888888"
set -g pane-active-border-style "fg=${thm_orange}"

# Status bar
set -g status-bg "${thm_orange}"
set -g window-status-current-format "#[fg=#111111] #I: #[fg=#00FF00]() #[fg=#111111]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev)#{?window_zoomed_flag,(Z),}"
set -g status-right "#[fg=#111111] #W - #S"
set -g status-left ""

# Modes
set -g clock-mode-colour "${thm_orange}"
set -g mode-style "fg=${thm_black} bg=${thm_orange} bold"

