# Geometry
no-keepaspect-window
no-border
autofit=652
geometry=0:0
# geometry=450x1080+2050+0


# Switching to uosc
# osc=no
osd-bar=no
border=no

# Volume
volume-max=150
volume=50

# Keep open after video end
keep-open

# Use GPU decoding by default
# vo=gpu
# hwdec=auto-safe

# Auto profiles
load-auto-profiles=yes
[mp3_profile]
profile-desc="Profile for .mp3 files"
profile-cond=filename:match"[.]mp3$" ~= nil
loop-playlist=inf

# UOSC options
# timeline_persistency='audio,paused'
